let text = "The quick brown fox jumps over the wall";
console.log(text);
console.log(text.length);
console.log(text.toLowerCase());
console.log(text.toUpperCase());
console.log(text[5]);
console.log(text.indexOf('o'));
console.log(text.lastIndexOf('o'));
console.log(text.startsWith());
console.log(text.endsWith('well'));
console.log(text.toLocaleLowerCase());
console.log(text.toLocaleUpperCase());
console.log(text.charAt('12'));
console.log(text.split(" "));
console.log(text.substr(1,6));
console.log(text.replace("brown","black"));
console.log(text.search("black"));
console.log(text.toString());
console.log(text.valueOf());

arr = ['one',true,32, ['1','2']];
arr2= ['hyderabad','chennai','mumbai'];
console.log(arr);
console.log(Array.isArray(arr));
console.log(arr.reverse());
console.log(arr[3]);
console.log(arr.concat(arr2));
arr2.unshift('chennai');
console.log(arr2);
console.log(arr2.copyWithin(2,0));
console.log(arr2.includes('hyderabad'));
console.log(arr.join());
console.log(arr.length);
console.log(arr2.lastIndexOf("chennai"));
console.log(arr2.push("kolkata"));
console.log(arr2.slice(1,3));
console.log(arr2.fill());
console.log(arr2.pop());
